type GridData = {
  readonly dialogue: string[]
  readonly grid: string[]
  readonly id: number
  readonly winConditions: string
  readonly instruction: string
  readonly help: string
}

type Grids = {
  readonly [index: number]: GridData
}

export const grids: Grids = {
  1: {
    dialogue: ["Bon ben… on part en mission.", "Avec toute l’équipe ?", "Ben oui… pas avec le pape !"],
    grid: [
      "nuit",
      "sable",
      "sept",
      "super",
      "talon",
      "voler",
      "piston",
      "poil",
      "téléphone",
      "tas",
      "serviette",
      "mecque",
      "moteur",
      "bras",
      "numéro",
      "diesel",
      "pile",
      "plume",
      "plage",
      "aide",
      "pied",
      "appel",
      "table",
      "chouette",
      "jour",
    ],
    id: 1,
    winConditions: "Rébus de 3 mots. Départ : Lune - Achille",
    instruction: "Appuyez-vous sur l’indice contextuel donné par les galets 11 pour résoudre le rébus final.",
    help: "Pensez aux synonymes, aux contraires, au sens propre, au sens figuré, aux liens directs et évidents.",
  },
  2: {
    dialogue: [
      "Euh… il n’y a pas que des hommes dans l’équipe !",
      "Ah oui c’est vrai. Depuis l’arrivée de la cheffe…",
      "C’est ça ! Fait l’innocent. Tu crois qu’on a rien vu ?",
    ],
    grid: [
      "martien",
      "être",
      "dernier",
      "amour",
      "contre",
      "pour",
      "avril",
      "avoir",
      "mars",
      "bulletin",
      "pluie",
      "sens",
      "éléphant",
      "humain",
      "mot",
      "haine",
      "voter",
      "singulier",
      "eux",
      "pluriel",
      "tique",
      "unique",
      "météo",
      "tasse",
      "premier",
    ],
    id: 2,
    winConditions: "Rébus de 3 mots. Départ : Lettre - Goutte",
    instruction:
      "Plusieurs associations sont possibles pour un même mot, alors essayez-les toutes pour voir où elles vous mènent.",
    help: "L’indice donné par les galets 11 peut être un rébus",
  },
  3: {
    dialogue: ["Bah tiens justement… Elle arrive.", "Houlala…", "Elle va peut être te déclarer sa flamme…"],
    grid: [
      "manchot",
      "vieux",
      "jet",
      "pot",
      "appareil",
      "raisin",
      "identité",
      "photo",
      "beau",
      "journal",
      "carré",
      "intime",
      "aîné",
      "vin",
      "idée",
      "chair",
      "frère",
      "fil",
      "poule",
      "rouge",
      "feu",
      "os",
      "dentaire",
      "papier",
      "fixe",
    ],
    id: 3,
    winConditions: "Rébus de 3 mots. Départ : Sec - Eau",
    instruction: "Désormais, à vous de voir si l’indice donné par les galets 11 est un rébus.",
    help: "En cas de besoin, tapez les deux mots envisagés dans un moteur de recherche et voyez si un lien fort apparaît.",
  },
  4: {
    dialogue: [
      "Bonjour Messieurs. J’irai droit au but. Une menace guette !",
      "Holala… Encore une guerre ! Pourtant il y a un truc pour arrêter ça !",
      "Ben voyons ! Quoi donc s’il vous plait !?",
    ],
    grid: [
      "dégât",
      "tour",
      "bon",
      "filet",
      "gare",
      "direction",
      "match",
      "mont",
      "créneau",
      "répare",
      "nul",
      "tisse",
      "sens",
      "france",
      "crête",
      "coq",
      "faux",
      "sinistre",
      "bricole",
      "lézard",
      "sommet",
      "nord",
      "miss",
      "marteau",
      "tennis",
    ],
    id: 4,
    winConditions: "Rébus de 3 mots. Départ : Mort - Blanc",
    instruction: "Amusez-vous bien !",
    help: "Avez-vous remarqué que d’une grille à une autre, les dialogues sont liés et racontent une histoire ?",
  },
  5: {
    dialogue: [
      "Très drôle. Bon. Assez rigolé ! Vous partez sur le champ.",
      "Mais… euh… cheffe, vous ne venez pas avec nous ?",
      "Je ne peux pas non.",
    ],
    grid: [
      "dôme",
      "perdre",
      "pas",
      "panier",
      "peu",
      "lait",
      "très",
      "beaucoup",
      "corne",
      "volé",
      "brume",
      "assez",
      "un",
      "entier",
      "place",
      "crabe",
      "déçu",
      "ravi",
      "premier",
      "âge",
      "sur",
      "nombre",
      "vache",
      "trace",
      "dessus",
    ],
    id: 5,
    winConditions: "Rébus de 3 mots. Départ : Brouillard - Pince",
    instruction: "Amusez-vous bien !",
    help: "Un adverbe est lié à un autre mot pour créer une expression avec un sens propre et particulier.",
  },
}
